apiVersion: apps/v1
kind: Deployment
metadata:
    name: pgadmin-deployment
spec:
    replicas: 2
    strategy:
        type: Recreate
    matchlabels:
        app: my-app
template:
    metadata:
        labels:
            app: my-app
    spec:
        container:
            - name: pgadmin-container
              image: dpage/pgadmin4
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: my-app
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer